name: Build PyQt App
on: [push] # Triggers every time you push code to GitHub

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller PyQt6  # Add any other libraries you use here
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        shell: bash

      - name: Build with PyInstaller
        run: |
          pyinstaller --windowed --onefile --paths krop --name "Krop" krop/__main__.py
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.os }}
          path: dist/